name: mattermost_api
description: An implementation of the Mattermost API as of 4.0.0.
version: 0.1.0
homepage: https://www.jeffmikels.com

environment:
  sdk: '>=2.17.1 <3.0.0'


dependencies:
  # Mattermost's API runs over standard http methods and websockets
  http: ^0.13.4
  intl: ^0.17.0
  meta: ^1.1.8
  

dev_dependencies:
  build_runner: ^2.1.11
  lints: ^1.0.0
  # openapi_generator_annotations: ^3.3.0
  # openapi_generator: ^3.3.0+1
  analyzer: 
  test: ^1.16.0
