name: mattermost_api
description: An implementation of the Mattermost API as of 4.0.0.
version: 0.1.5
homepage: https://www.jeffmikels.com
repository: https://github.com/jeffmikels/mattermost_api_dart

environment:
  sdk: '>=2.17.1 <3.0.0'


dependencies:
  # Mattermost's API runs over standard http methods and websockets
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
